- README.md
- browser-config.js
- common-config.js
- node-config.js
- package.json
@omsmith : I thought I would take a few minutes to create this for the [suggested enhancement](https://github.com/Brightspace/eslint-config-brightspace/issues/4).
This change simply utilizes the `es6` environment and `node` environments, and sets up the suggested rule override for `prefer-const`.
The `es6` environment includes all the `ecmaFeatures` except for `modules`, and can be found at the bottom of [this file](https://github.com/eslint/eslint/blob/master/conf/environments.js).  We can list them individually if you want, rather than including all the ones in the `es6` defined environment - it will just require more maintenance.  For the purpose of linting, I'm ok with just utilizing the environment unless it causes problems in dev. 
I've added an override for `prefer-const`.  I am …
> Adding node-config.  Adding "prefer-const" rule.

- browser-config.js
- index.js
- node-config.js
- package.json
- polymer-config.js
- react-config.js
- wct-config.js
@dbatiste our existing configuration blows up if consumers try to use eslint 4, so figured it was time to upgrade this. Was also able to extend things a little easier using eslint's built-in "extend".
> upgrading to eslint 4 from 2 and improving how we extend configurations

- common-config.js
@CodeBaboon noticed some inconsistent spacing in a unrelated pr.  Per https://eslint.org/docs/rules/#stylistic-issues spacing in parens and other stylistic issues aren't enforced by default.
I want this change so that these mistakes can be auto fixed using  `eslint --fix`
> add space-in-parens error

- README.md
- lit-config.js
Enabled all the lit rules with the exception of [no-template-map](https://github.com/43081j/eslint-plugin-lit/blob/master/docs/rules/no-template-map.md).
I also considered enabling the `strict` rule to error/warning since `"use strict";` is redundant inside of modules, but we may still use it in demo pages so I kept this rule consistent with our polymer-3 config.  Tests too, but we'll likely have a different config for tests anyway.
Let me know if you disagree with any of the rules.  There are all listed at the bottom here... https://github.com/43081j/eslint-plugin-lit
> Adding eslint config for lit elements.

- lit-config.js
- package.json
This would cause chaos adding to the polymer configs, but we can enforce this going forward.
> Add const and var rules to lit config

- README.md
- lit-config.js
- package.json
- polymer-3-config.js
- sort-member-config.js
This PR was inspired from a comment @m6jones left on my [pr](https://github.com/BrightspaceHypermediaComponents/organizations/pull/76#discussion_r291747845).  I personally find that comments like that end up not being followed consistently unless you codify the rules somewhere.  So hopefully this works for both of you.
Currently this is configured for just one config, but if we're ok with introducing this plugin we can certainly expand it to the other configs.
As an example this was run against BrightspaceHypermediaComponents/organizations and I got the following output:
```
> eslint . --ext .js,.html test/**/*.js test/**/*.html demo/**/*.js demo/**/*.html
C:\d2l\github\organizations\components\d2l-organization-date\d2l-organization-date.js
26:2  error  Expected static getter template to …
```
> initial configuration for class member sorting

- lit-config.js
This prevents:
```javascript
try {
// something
} catch {
// sometning
}
```
Empty catch binding [isn't actually a thing yet](https://github.com/tc39/proposal-optional-catch-binding), and the version of Babel used by `polymer build` isn't configured to handle it, so using it causes build failures that look like this:
```
{ err:
“This experimental syntax requires enabling the parser plugin: ‘optionalCatchBinding’ (211:9)”
}
```
> preventing optional catch binding

- common-config.js
- package.json
Added [object-curly-spacing](https://eslint.org/docs/rules/object-curly-spacing)
`This rule enforces consistent spacing inside braces of object literals, destructuring assignments, and import/export specifiers.`
> Object curly spacing

- common-config.js
- package.json
Tackling a story we've had sitting around for a while.  Having this linting rule would have saved us from a my courses hotfix after we toggled on some very old code triggered by a very specific edge case.  Thoughts?
https://eslint.org/docs/rules/no-use-before-define
> Add no-use-before-define for variables and classes

- browser-config.js
[babel-eslint](https://github.com/babel/babel-eslint) has moved to [@babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser)
> Upgrade to @babel/eslint-parser to support dynamic imports

- package.json
Should have done this with `0.13.0` but this will make it clearer earlier that it's required, and with npm 7 it will install it automatically.
> Add @babel/eslint-parser as a peer dependency

- lit-config.js
- polymer-sort-member-config.js
- sort-member-config.js
While using `lit-config` extension in our project, I realized that having non-paired private accessors (i.e. private getter with no setter or vice versa) would intertwine the private accessors and private methods when sorting. So I added another group called "private-accessors" which sorts standalone getters first then sorts standalone setters second. See below for a better explanation.
This was the behaviour **before** this change:
```js
// private accessor pairs group
get _method4() {}
set _method4(arg) {}
// private methods group
get _method1() {} // <-- private getter falls under "private-methods" group
_method2() {} // <-- private method
set _method3(arg) {} // <-- private setter falls under "private-methods" group
get _method5() {} // <-- private getter falls under "private-methods" …
```
> feat: Add private accessors group to sort-member-config

- lit-config.js
- polymer-sort-member-config.js
- sort-member-config.js
I encountered the same exact issue with standalone public accessors as I did with private accessors in #41.
> fix: Add public accessors group to sort-member-config

- README.md
- lit-config.js
An unexpected problem I noticed with Lit 2.0 is that it no longer works with extension-less imports. This [was apparently intentional](https://github.com/lit/lit/issues/1986) to enable import-map support.
So to catch these errors, I'm adding the "import" plugin to our eslint config. It'll now fail if you forget to include the `.js` extension in your imports.
> feat: adding import plugin to catch extension-less imports

- README.md
- lit-config.js
Unfortunately this breaks things like:
```javascript
import { LitElement } from 'lit';
```
And we can't have that. So reverting this out for now until I can find a better solution.
> Reverting import plugin

- README.md
- lit-config.js
Attempt 2. The `ignorePackages` flag appears to do exactly what we want, in that it'll allow `import { LitElement } from 'lit-element';` (a package) but catch file imports that are missing extensions. Hat-tip to @svanherk for noticing it. 🎩
> feat: restoring the "import" plugin but ignoring packages this time

- package.json
I upgraded a few repos to use eslint version 8, and now I'm seeing warnings about our config requiring eslint 7. Their [documentation](https://eslint.org/docs/developer-guide/shareable-configs#publishing-a-shareable-config) recommends using the `>=` syntax to future-proof your configs.
> fix: future-proof peer dependencies

- common-config.js
Allow `==` for `null` literal to avoid the need to do `value !== null && value !== undefined` whenever wanting to check if the `value` exists without accidently having `0` and `false` be included in that check (i.e. doing `if (!value)`). This still requires `===` for all other cases. Tried this with rubrics and the behaviour worked as desired
https://eslint.org/docs/rules/eqeqeq#allow-null
> feat: adjust how `null` `eqeqeq` rule works

- browser-config.js
- lit-config.js
I've been working in a non-Lit context for the past few days in repos that just use the `browser-config`. I noticed that a lot of the rules we're used to in Lit aren't being applied. This moves a lot of the browser-y things from the Lit config up to its parent. 
I ran this in core and this resulted in no errors, as expected. But this could have a pretty big impact on repos using the browser config directly, or the Polymer configs indirectly -- it'll be a minor (which is major at `0.x`) bump for that reason.
> feat: moving some settings from lit to browser config

- README.md
- browser-config.js
- package.json
Imports with absolute paths have broken a few BSI builds lately, so it was time to make this a linting error scenario [using this plugin](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-absolute-path.md).
I'm also making the plugins used by our config `peerDependencies`, which NPM >= 7 will install automatically and removes the need for consumers to list these as project dependencies. This shouldn't make our eventual migration to the [new config file format](https://eslint.org/blog/2022/08/new-config-system-part-1/) any more difficult.
> feat: add no-absolute-path plugin

- common-config.js
Prevents stuff like `temp1 == temp2 ? true : false`. Can also be auto fixed in most simple cases.
https://eslint.org/docs/latest/rules/no-unneeded-ternary
> feat: add rule `no-unneeded-ternary`

- common-config.js
Quick search suggests this is a recommend rule:
> Although possible, there aren’t any good reasons to use these primitive wrappers as constructors. They tend to confuse other developers more than anything else because they seem like they should act as primitives, but they do not.
> ~https://eslint.org/docs/latest/rules/no-new-wrappers
> Never use new on the primitive object wrappers (Boolean, Number, String, Symbol), nor include them in type annotations.
> ~https://google.github.io/styleguide/jsguide.html#disallowed-features-wrapper-objects
Happy to just close the PR if we don't quickly trend towards an obvious "we should add this".
> chore(common-config): add `no-new-wrappers`.

- browser-config.js
- common-config.js
I believe `let` or `const` is preferred over `var` in most situations. Thoughts on enabling `no-var` for everyone?
I'm coming from Node.js so alternatively, thoughts on enabling it for `node-config` if not for everyone?
> feat(common-config): add 'no-var' to all contexts.

- lit-config.js
We're making use of `willUpdate` in folio-app and noticed that our linting config doesn't treat it as a lit lifecycle method. Adding a few others from the documentation while I'm here.
> Add additional lit lifecycle methods

- lit-config.js
Lang files currently use a mix of single quotes, double quotes, and backticks, and override the quotes rule either in each file or in their own eslint configs. This disables that rule globally so we don't need to do it everywhere manually.
> Disable quotes rule for lang files

- .github/workflows/release.yml
The `brightspace-bot` and `D2L_GITHUB_TOKEN` are no longer needed for `release` workflows. Instead, we have a [new `D2L_RELEASE_TOKEN`](https://github.com/Brightspace/repo-settings/blob/main/docs/release_action_setup.md) that has the ability to bypass the repo ruleset (configured in https://github.com/Brightspace/repo-settings/pull/1537) and org-level ruleset.
Before merging, I will:
- Confirm the new ruleset matches the old branch protection rule before deleting it
- Remove `brightspace-bot` as a repo contributor
- Confirm the `D2L_RELEASE_TOKEN` is available and remove this repo's access to `D2L_GITHUB_TOKEN`
> GAUD-292 - Use new release token

- sort-member-config.js
Class properties cannot be required to be sorted because their initialization is executed in order and they may reference each other. I'm kind of baffled this is even an option.
It's equivalent to requiring these be sorted:
```js
const b = 1;
const a = b;
```
> Do not require sorting class properties

- package-lock.json
- package.json
Version 7 seems to fail parsing when used with eslint9 flat configs. So bumping the version is necessary to update repos to eslint9. (e.g. this [update](https://github.com/BrightspaceUI/core/pull/5100) is currently failing because of the limit to the version).
[CHANGELOG.md](https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/05bb69f7466f2077abf7ed9f9edf662c351fbd6e/CHANGELOG.md) lists as breaking changes only dropping node 12 and 14
> fix: allow eslint-plugin-html 8

- index.js
Running into a `no-unused-vars` error [here](https://github.com/BrightspaceUI/testing/pull/527/files#diff-12c5b59babab824650a00f2b88cd8eeb9fa04dbfed5bbed3e67b14b71ca9aae2R77) because the first item in a destructured object followed by a rest isn't used:
```javascript
const {a, ...b} = c;
return b;
```
This is just an immutable way to quickly filter an object, and is similar to the first unused argument of a function being ignored:
```javascript
function a(b, c) {
return c + 1;
}
```
> Ignore unused rest vars

- browser-config.js
- index.js
The `no-restricted-syntax` was not being set by the recommended rules but by an override on `browser-config.js`. The rule was explicitly set [here](https://github.com/Brightspace/eslint-config-brightspace/pull/28), at that point the syntax was not fully supported which now [is not the case](https://caniuse.com/?search=optional%20catch%20binding).
> fix: Properly remove `no-restricted-syntax`

- configs/base.js
[GAUD-7526](https://desire2learn.atlassian.net/browse/GAUD-7526): eslint-config: Allow unused vars/args in destructured arrays
Allows vars/args in destructured arrays to be unused if they either start with `_` or are exactly `gc`.
Example:
```javascript
([gc, v]) => v === version
```
or
```javascript
const [_name, _phone, address] = user.profile;
```
where `_name` and `_phone` would never be used
[GAUD-7526]: https://desire2learn.atlassian.net/browse/GAUD-7526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow unused vars/args in destructured arrays
